import { invoke } from '@tauri-apps/api/core';
import type {
	AppState,
	CoderStatus,
	ContainerStatus,
	ContentSearchOptions,
	ContentSearchResult,
	DeviceCode,
	DirEntry,
	EditorConfig,
	FileSearchOptions,
	FileSearchResult,
	GitFileBlame,
	GitStatusEntry,
	HfIdentity,
	LspCompletionList,
	LspHover,
	LspLocation,
	LspPosition,
	ProjectComposeStatus,
	ReadFileResult,
	SlackBotProfile,
	SlackIdentity,
	SlackMessage,
	SlackSession,
	SlackStatus,
	SlackUserSummary,
	StatResult,
	SystemTheme,
	TerminalOpenRequest,
	Workspace,
	WriteFileResult,
} from './protocol';

// Single auditable surface for all Tauri commands. Components MUST go through this.
export const ipc = {
	workspace: {
		openLocal: (path: string) => invoke<Workspace>('workspace_open_local', { path }),
		removeFolder: (path: string) => invoke<Workspace>('workspace_remove_folder', { path }),
		setActiveFolder: (path: string) => invoke<Workspace>('workspace_set_active_folder', { path }),
		active: () => invoke<Workspace | null>('workspace_active'),
		list: () => invoke<Workspace[]>('workspace_list'),
	},
	fs: {
		readDir: (path: string) => invoke<DirEntry[]>('fs_read_dir', { path }),
		collectPaths: (maxDepth: number) => invoke<string[]>('fs_collect_paths', { maxDepth }),
		readFile: (path: string) => invoke<ReadFileResult>('fs_read_file', { path }),
		writeFile: (path: string, text: string) => invoke<WriteFileResult>('fs_write_file', { path, text }),
		stat: (path: string) => invoke<StatResult>('fs_stat', { path }),
		absolutePath: (path: string) => invoke<string>('fs_absolute_path', { path }),
		trash: (path: string) => invoke<void>('fs_trash', { path }),
		delete: (path: string) => invoke<void>('fs_delete', { path }),
		gitStatusEntries: (paths: string[]) => invoke<GitStatusEntry[]>('fs_git_status_entries', { paths }),
		gitRestorePaths: (paths: string[]) => invoke<void>('fs_git_restore_paths', { paths }),
		gitBlame: (path: string) => invoke<GitFileBlame | null>('fs_git_blame', { path }),
		gitHeadContent: (path: string) => invoke<string | null>('fs_git_head_content', { path }),
	},
	search: {
		files: (options: FileSearchOptions) => invoke<FileSearchResult[]>('search_files', { options }),
		content: (options: ContentSearchOptions) => invoke<ContentSearchResult>('search_content', { options }),
	},
	appState: {
		load: () => invoke<AppState>('app_state_load'),
		save: (appState: AppState) => invoke<void>('app_state_save', { appState }),
	},
	system: {
		theme: () => invoke<SystemTheme>('system_theme'),
	},
	editorconfig: {
		forPath: (path: string) => invoke<EditorConfig>('editorconfig_for_path', { path }),
	},
	container: {
		status: () => invoke<ContainerStatus>('container_status'),
		setup: () => invoke<ContainerStatus>('container_setup'),
		pause: () => invoke<ContainerStatus>('container_pause'),
		resume: () => invoke<ContainerStatus>('container_resume'),
		rebuild: () => invoke<ContainerStatus>('container_rebuild'),
		stop: () => invoke<ContainerStatus>('container_stop'),
		teardown: () => invoke<ContainerStatus>('container_teardown'),
		applyBoundFolders: () => invoke<ContainerStatus>('container_apply_bound_folders'),
		renderCompose: () => invoke<string>('container_render_compose'),
	},
	projectCompose: {
		status: (folderPath: string) => invoke<ProjectComposeStatus>('project_compose_status', { folderPath }),
		up: (folderPath: string) => invoke<ProjectComposeStatus>('project_compose_up', { folderPath }),
		pause: (folderPath: string) => invoke<ProjectComposeStatus>('project_compose_pause', { folderPath }),
		resume: (folderPath: string) => invoke<ProjectComposeStatus>('project_compose_resume', { folderPath }),
		rebuild: (folderPath: string) => invoke<ProjectComposeStatus>('project_compose_rebuild', { folderPath }),
		stop: (folderPath: string) => invoke<ProjectComposeStatus>('project_compose_stop', { folderPath }),
		down: (folderPath: string) => invoke<ProjectComposeStatus>('project_compose_down', { folderPath }),
		serviceStart: (folderPath: string, service: string) =>
			invoke<ProjectComposeStatus>('project_compose_service_start', { folderPath, service }),
		serviceStop: (folderPath: string, service: string) =>
			invoke<ProjectComposeStatus>('project_compose_service_stop', { folderPath, service }),
		serviceRestart: (folderPath: string, service: string) =>
			invoke<ProjectComposeStatus>('project_compose_service_restart', { folderPath, service }),
	},
	composeLogs: {
		open: (folderPath: string, service: string) => invoke<string>('compose_logs_open', { folderPath, service }),
		close: (streamId: string) => invoke<void>('compose_logs_close', { streamId }),
	},
	terminal: {
		open: (request: TerminalOpenRequest) => invoke<string>('terminal_open', { request }),
		write: (streamId: string, data: string) => invoke<void>('terminal_write', { streamId, data }),
		resize: (streamId: string, cols: number, rows: number) => invoke<void>('terminal_resize', { streamId, cols, rows }),
		close: (streamId: string) => invoke<void>('terminal_close', { streamId }),
	},
	lsp: {
		open: (path: string, languageId: string, text: string) => invoke<void>('lsp_open', { path, languageId, text }),
		update: (path: string, languageId: string, text: string) => invoke<void>('lsp_update', { path, languageId, text }),
		close: (path: string, languageId: string) => invoke<void>('lsp_close', { path, languageId }),
		hover: (path: string, languageId: string, position: LspPosition) =>
			invoke<LspHover | null>('lsp_hover', { path, languageId, position }),
		completion: (path: string, languageId: string, position: LspPosition) =>
			invoke<LspCompletionList>('lsp_completion', { path, languageId, position }),
		definition: (path: string, languageId: string, position: LspPosition) =>
			invoke<LspLocation | null>('lsp_definition', { path, languageId, position }),
	},
	slack: {
		setToken: (token: string) => invoke<SlackIdentity>('slack_set_token', { token }),
		status: () => invoke<SlackStatus>('slack_status'),
		clearToken: () => invoke<void>('slack_clear_token'),
		listDmBots: () => invoke<SlackBotProfile[]>('slack_list_dm_bots'),
		selectBot: (profile: SlackBotProfile) => invoke<void>('slack_select_bot', { profile }),
		clearBot: () => invoke<void>('slack_clear_bot'),
		getActiveBot: () => invoke<SlackBotProfile | null>('slack_get_active_bot'),
		setPanelVisible: (visible: boolean) => invoke<void>('slack_set_panel_visible', { visible }),
		setWindowFocused: (focused: boolean) => invoke<void>('slack_set_window_focused', { focused }),
		listSessions: (channel: string) => invoke<SlackSession[]>('slack_list_sessions', { channel }),
		getThread: (channel: string, threadTs: string) => invoke<SlackMessage[]>('slack_get_thread', { channel, threadTs }),
		setActiveThread: (threadTs: string | null) => invoke<void>('slack_set_active_thread', { threadTs }),
		getUser: (userId: string) => invoke<SlackUserSummary>('slack_get_user', { userId }),
		markRead: (channel: string, ts: string) => invoke<void>('slack_mark_read', { channel, ts }),
		postMessage: (channel: string, threadTs: string | null, text: string) =>
			invoke<SlackMessage>('slack_post_message', { channel, threadTs, text }),
	},
	coder: {
		status: () => invoke<CoderStatus>('coder_status'),
		startDeviceFlow: () => invoke<DeviceCode>('coder_start_device_flow'),
		pollDeviceCode: (code: DeviceCode) => invoke<HfIdentity>('coder_poll_device_code', { code }),
		signOut: () => invoke<void>('coder_sign_out'),
		send: (text: string) => invoke<void>('coder_send', { text }),
		abort: () => invoke<void>('coder_abort'),
	},
} as const;
