//! Generate the workspace's `.moon/compose.yaml`.
//!
//! Output shape (anchored by ADR 0007 + the
//! [`specs/containers.md`](../../../specs/containers.md) "Workspace
//! config" section):
//!
//! ```yaml
//! # Generated by moon-ide on first opt-in. Edit freely; moon-ide
//! # will only regenerate this file on explicit "Reset compose".
//!
//! name: moon-ws-<8 hex>
//!
//! include:
//!   - ../moon-landing/docker-compose.yml
//!
//! services:
//!   dev:
//!     image: moon-base:dev
//!     init: true
//!     working_dir: /workspace
//!     volumes:
//!       - ../:/workspace
//!     command: ["sleep", "infinity"]
//!
//! x-moon:
//!   shell-service: dev
//! ```
//!
//! Why a string template, not `serde_yaml`
//! ----------------------------------------
//!
//! The `serde_yaml` crate has been unmaintained since late 2023,
//! and the structure we emit is small + fixed. Hand-rendered we
//! get exact control over comments, key order, and whitespace —
//! the file is meant to be human-readable and human-editable, not
//! parsed back by us. If a future need to read it back appears,
//! we'll reach for a maintained YAML crate at that point, not
//! preemptively.
//!
//! Path conventions
//! ----------------
//!
//! Every relative path inside the file is resolved by `docker
//! compose` relative to the **compose file's** directory — i.e.
//! `<workspace>/.moon/`. So:
//!
//! - `volumes: [../:/workspace]` mounts the workspace root.
//! - `include: [../moon-landing/docker-compose.yml]` resolves to
//!   the discovered file. Volumes inside the *included* file are
//!   in turn resolved relative to *that* file's directory, which
//!   is the behaviour each project already relies on — moon-ide's
//!   wrapping is transparent.
//!
//! This module is only responsible for producing the **string
//! contents** of the file. Writing it to disk, opt-in prompting,
//! and the surrounding lifecycle live in callers.

use std::fmt::Write as _;

use camino::Utf8Path;

use crate::project::ProjectName;

/// How the generator should populate the `dev` service and the
/// `include:` list.
#[derive(Debug, Clone)]
pub struct ComposeRenderOptions<'a> {
	/// `name:` value — the compose project identifier; see
	/// [`crate::project`].
	pub project: &'a ProjectName,
	/// Image reference for the `dev` service. While moon-base is
	/// in tree but unpublished we default callers to
	/// `moon-base:dev` (a local build). Once a published tag
	/// exists this'll move to `huggingface/moon-base:<tag>`.
	pub dev_image: &'a str,
	/// Compose files to wire into `include:`, given as paths
	/// relative to the **workspace root**. Empty is fine — the
	/// `include:` block is omitted entirely in that case.
	pub include_files: &'a [&'a Utf8Path],
}

/// Result of [`generate_compose`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComposeRender {
	/// The full file contents, ready to be written to
	/// `<workspace>/.moon/compose.yaml`.
	pub yaml: String,
}

/// Render the workspace's `.moon/compose.yaml`.
pub fn generate_compose(options: ComposeRenderOptions<'_>) -> ComposeRender {
	let mut yaml = String::new();
	let _ = writeln!(yaml, "# Generated by moon-ide on first opt-in. Edit freely;");
	let _ = writeln!(yaml, "# moon-ide regenerates this file only on explicit");
	let _ = writeln!(yaml, "# \"Container: Reset compose\".");
	let _ = writeln!(yaml, "#");
	let _ = writeln!(yaml, "# Architecture: ../specs/containers.md (relative to the");
	let _ = writeln!(yaml, "# moon-ide repository, not this workspace).");
	let _ = writeln!(yaml);

	let _ = writeln!(yaml, "name: {}", options.project);
	let _ = writeln!(yaml);

	if !options.include_files.is_empty() {
		let _ = writeln!(yaml, "include:");
		for rel in options.include_files {
			// Compose resolves include paths relative to the
			// compose file's directory (`<workspace>/.moon/`); the
			// caller hands us paths relative to the workspace
			// root, so we prefix `../` on the way in.
			let _ = writeln!(yaml, "  - ../{}", rel.as_str());
		}
		let _ = writeln!(yaml);
	}

	let _ = writeln!(yaml, "services:");
	let _ = writeln!(yaml, "  dev:");
	let _ = writeln!(yaml, "    image: {}", options.dev_image);
	// `init: true` reaps zombie processes for tools like watch
	// loops and `bun install`'s child workers — the same reason
	// `tini` ships in most "polyglot dev shell" base images.
	let _ = writeln!(yaml, "    init: true");
	let _ = writeln!(yaml, "    working_dir: /workspace");
	let _ = writeln!(yaml, "    volumes:");
	let _ = writeln!(yaml, "      - ../:/workspace");
	// `sleep infinity` is the conventional "keep this container
	// alive so we can `docker exec` into it" command. Phase 2.1
	// will keep the same shape; routed execution attaches via
	// `docker exec`, never via the entrypoint.
	let _ = writeln!(yaml, "    command: [\"sleep\", \"infinity\"]");
	let _ = writeln!(yaml);

	let _ = writeln!(yaml, "x-moon:");
	// The "which service do new terminals attach to?" key. Single
	// service today; 2.4 promotes this to a user-pickable default.
	let _ = writeln!(yaml, "  shell-service: dev");

	ComposeRender { yaml }
}

#[cfg(test)]
mod tests {
	use camino::Utf8Path;

	use super::*;
	use crate::project::project_name_for;

	#[test]
	fn minimal_workspace_renders_without_include_block() {
		let project = project_name_for(Utf8Path::new("/x"));
		let render = generate_compose(ComposeRenderOptions {
			project: &project,
			dev_image: "moon-base:dev",
			include_files: &[],
		});

		assert!(render.yaml.contains(&format!("name: {project}")));
		assert!(render.yaml.contains("image: moon-base:dev"));
		assert!(render.yaml.contains("command: [\"sleep\", \"infinity\"]"));
		assert!(render.yaml.contains("shell-service: dev"));
		// No included files → no `include:` key at all (compose
		// doesn't accept an empty list cleanly in every version).
		assert!(!render.yaml.contains("include:"));
	}

	#[test]
	fn include_block_uses_dotdot_for_compose_file_relative_paths() {
		let project = project_name_for(Utf8Path::new("/x"));
		let landing = Utf8Path::new("moon-landing/docker-compose.yml");
		let other = Utf8Path::new("infra/compose.yaml");
		let render = generate_compose(ComposeRenderOptions {
			project: &project,
			dev_image: "moon-base:dev",
			include_files: &[landing, other],
		});

		assert!(render.yaml.contains("include:"));
		assert!(render.yaml.contains("- ../moon-landing/docker-compose.yml"));
		assert!(render.yaml.contains("- ../infra/compose.yaml"));
	}

	#[test]
	fn output_is_deterministic_for_same_input() {
		let project = project_name_for(Utf8Path::new("/x"));
		let landing = Utf8Path::new("moon-landing/docker-compose.yml");
		let opts = ComposeRenderOptions {
			project: &project,
			dev_image: "moon-base:dev",
			include_files: &[landing],
		};
		let a = generate_compose(opts.clone());
		let b = generate_compose(opts);
		assert_eq!(a, b);
	}

	#[test]
	fn dev_image_override_lands_in_output() {
		// Once we publish, callers will pass the registry tag.
		let project = project_name_for(Utf8Path::new("/x"));
		let render = generate_compose(ComposeRenderOptions {
			project: &project,
			dev_image: "huggingface/moon-base:0.1",
			include_files: &[],
		});
		assert!(render.yaml.contains("image: huggingface/moon-base:0.1"));
	}

	#[test]
	fn workspace_root_is_mounted_at_workspace() {
		let project = project_name_for(Utf8Path::new("/x"));
		let render = generate_compose(ComposeRenderOptions {
			project: &project,
			dev_image: "moon-base:dev",
			include_files: &[],
		});
		assert!(render.yaml.contains("- ../:/workspace"));
		assert!(render.yaml.contains("working_dir: /workspace"));
	}
}
