//! Generate the workspace's `compose.yaml`.
//!
//! Output shape (anchored by ADR 0007 + the
//! [`specs/containers.md`](../../../specs/containers.md) "Workspace
//! config" section):
//!
//! ```yaml
//! # Generated by moon-ide. Edit `bound-folders.json` to change
//! # what's mounted; this file is rewritten on every change to the
//! # bound-folder set.
//!
//! name: moon-ws-default
//!
//! include:
//!   - /home/me/code/moon-landing/docker-compose.yml
//!
//! services:
//!   dev:
//!     image: moon-base:dev
//!     init: true
//!     working_dir: /workspace
//!     volumes:
//!       - /home/me/code/moon-landing:/workspace/moon-landing
//!       - /home/me/code/moon-ide:/workspace/moon-ide
//!     command: ["sleep", "infinity"]
//!
//! x-moon:
//!   shell-service: dev
//! ```
//!
//! Path strategy
//! -------------
//!
//! The compose file lives at `~/.local/share/moon-ide/workspaces/
//! <id>/compose.yaml` — outside any specific repo. Every path
//! inside the file is therefore **absolute**:
//!
//! - `volumes:` — host-side absolute paths to each bound folder,
//!   mounted at `/workspace/<basename>` inside the container.
//! - `include:` — absolute paths to discovered project compose
//!   files. Compose still resolves their internal relative paths
//!   relative to *their* directory, which is what each repo
//!   expects.
//!
//! This is the post-2.5 redesign — pre-2.5 the file lived at
//! `<workspace>/.moon/compose.yaml` and used `../`-relative paths.
//! See [`specs/decisions/0007-compose-and-moon-base.md`](../../../specs/decisions/0007-compose-and-moon-base.md#amendment-2026-04-29-state-dir-and-multi-folder-mounts).
//!
//! Why a string template, not `serde_yaml`
//! ----------------------------------------
//!
//! The `serde_yaml` crate has been unmaintained since late 2023
//! and the structure we emit is small + fixed. Hand-rendered we
//! get exact control over comments, key order, and whitespace —
//! the file is meant to be human-readable, not parsed back by us.
//! If a future need to read it back appears we'll reach for a
//! maintained YAML crate at that point, not preemptively.

use std::fmt::Write as _;

use camino::{Utf8Path, Utf8PathBuf};

use crate::project::ProjectName;

/// One folder mounted into the dev container.
///
/// `mount_name` is the segment placed under `/workspace/`; for a
/// folder at `/home/me/code/moon-landing` it'll be
/// `moon-landing`. Callers are responsible for mount-name
/// uniqueness within a workspace (the registry layer is the
/// natural enforcement point — see
/// [`specs/roadmaps/phase-02-containers.md`](../../../specs/roadmaps/phase-02-containers.md#pending-redesign-workspace--folder)).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BoundMount {
	/// Absolute host-side path. Written verbatim into `volumes:`.
	pub host_path: Utf8PathBuf,
	/// Container-side directory name (the basename portion of
	/// `/workspace/<name>`). Validated by the caller — this layer
	/// trusts the input.
	pub mount_name: String,
}

/// How the generator should populate the `dev` service and the
/// `include:` list.
#[derive(Debug, Clone)]
pub struct ComposeRenderOptions<'a> {
	/// `name:` value — the compose project identifier; see
	/// [`crate::project`].
	pub project: &'a ProjectName,
	/// Image reference for the `dev` service. While moon-base is
	/// in tree but unpublished we default callers to
	/// `moon-base:dev` (a local build). Once a published tag
	/// exists this'll move to `huggingface/moon-base:<tag>`.
	pub dev_image: &'a str,
	/// Bind-mount entries for the `dev` service. Empty is fine
	/// — we still emit `volumes: []` (compose tolerates it) so
	/// the generator's output is consistent. In practice the IDE
	/// only writes this file once at least one folder is bound.
	pub bound_mounts: &'a [BoundMount],
	/// Compose files to wire into `include:`, given as absolute
	/// paths. Empty is fine — the `include:` block is omitted in
	/// that case (some compose versions reject an empty list).
	pub include_files: &'a [&'a Utf8Path],
}

/// Result of [`generate_compose`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComposeRender {
	/// The full file contents, ready to be written to
	/// `<state_dir>/compose.yaml`.
	pub yaml: String,
}

/// Render the workspace's `compose.yaml`.
pub fn generate_compose(options: ComposeRenderOptions<'_>) -> ComposeRender {
	let mut yaml = String::new();
	let _ = writeln!(yaml, "# Generated by moon-ide. Edit `bound-folders.json` to");
	let _ = writeln!(yaml, "# change what's mounted; this file is rewritten on every");
	let _ = writeln!(yaml, "# change to the bound-folder set.");
	let _ = writeln!(yaml, "#");
	let _ = writeln!(yaml, "# Architecture: see specs/containers.md in the moon-ide");
	let _ = writeln!(yaml, "# repository.");
	let _ = writeln!(yaml);

	let _ = writeln!(yaml, "name: {}", options.project);
	let _ = writeln!(yaml);

	if !options.include_files.is_empty() {
		let _ = writeln!(yaml, "include:");
		for include in options.include_files {
			// Absolute paths — the compose file lives outside any
			// project, so there's no useful base to make these
			// relative to.
			let _ = writeln!(yaml, "  - {}", include.as_str());
		}
		let _ = writeln!(yaml);
	}

	let _ = writeln!(yaml, "services:");
	let _ = writeln!(yaml, "  dev:");
	let _ = writeln!(yaml, "    image: {}", options.dev_image);
	// `init: true` reaps zombie processes for tools like watch
	// loops and `bun install`'s child workers — the same reason
	// `tini` ships in most "polyglot dev shell" base images.
	let _ = writeln!(yaml, "    init: true");
	let _ = writeln!(yaml, "    working_dir: /workspace");
	let _ = writeln!(yaml, "    volumes:");
	if options.bound_mounts.is_empty() {
		// Empty list is valid YAML and compose accepts it; this
		// keeps the structure consistent for the no-folder edge
		// case.
		let _ = writeln!(yaml, "      []");
	} else {
		for mount in options.bound_mounts {
			let _ = writeln!(
				yaml,
				"      - {host}:/workspace/{name}",
				host = mount.host_path.as_str(),
				name = mount.mount_name,
			);
		}
	}
	// `sleep infinity` is the conventional "keep this container
	// alive so we can `docker exec` into it" command. Phase 2.1
	// will keep the same shape; routed execution attaches via
	// `docker exec`, never via the entrypoint.
	let _ = writeln!(yaml, "    command: [\"sleep\", \"infinity\"]");
	let _ = writeln!(yaml);

	let _ = writeln!(yaml, "x-moon:");
	// The "which service do new terminals attach to?" key. Single
	// service today; 2.4 promotes this to a user-pickable default.
	let _ = writeln!(yaml, "  shell-service: dev");

	ComposeRender { yaml }
}

#[cfg(test)]
mod tests {
	use camino::{Utf8Path, Utf8PathBuf};

	use super::*;
	use crate::project::project_name_for_id;

	fn project() -> ProjectName {
		project_name_for_id("default").unwrap()
	}

	fn mount(host: &str, name: &str) -> BoundMount {
		BoundMount {
			host_path: Utf8PathBuf::from(host),
			mount_name: name.to_owned(),
		}
	}

	#[test]
	fn no_folders_renders_empty_volumes_list() {
		let project = project();
		let render = generate_compose(ComposeRenderOptions {
			project: &project,
			dev_image: "moon-base:dev",
			bound_mounts: &[],
			include_files: &[],
		});

		assert!(render.yaml.contains("name: moon-ws-default"));
		assert!(render.yaml.contains("    volumes:\n      []"));
		// No bound folders → no include block.
		assert!(!render.yaml.contains("include:"));
	}

	#[test]
	fn bound_folders_render_as_volume_mounts_under_slash_workspace() {
		let project = project();
		let mounts = [
			mount("/home/me/code/moon-landing", "moon-landing"),
			mount("/home/me/code/moon-ide", "moon-ide"),
		];
		let render = generate_compose(ComposeRenderOptions {
			project: &project,
			dev_image: "moon-base:dev",
			bound_mounts: &mounts,
			include_files: &[],
		});

		assert!(render
			.yaml
			.contains("- /home/me/code/moon-landing:/workspace/moon-landing"));
		assert!(render.yaml.contains("- /home/me/code/moon-ide:/workspace/moon-ide"));
		assert!(render.yaml.contains("working_dir: /workspace"));
	}

	#[test]
	fn include_block_uses_absolute_paths() {
		let project = project();
		let landing = Utf8Path::new("/home/me/code/moon-landing/docker-compose.yml");
		let other = Utf8Path::new("/home/me/code/infra/compose.yaml");
		let render = generate_compose(ComposeRenderOptions {
			project: &project,
			dev_image: "moon-base:dev",
			bound_mounts: &[],
			include_files: &[landing, other],
		});

		assert!(render.yaml.contains("include:"));
		assert!(render.yaml.contains("- /home/me/code/moon-landing/docker-compose.yml"));
		assert!(render.yaml.contains("- /home/me/code/infra/compose.yaml"));
		// No `../` prefix anymore — the file lives outside any repo.
		assert!(!render.yaml.contains("- ../"));
	}

	#[test]
	fn output_is_deterministic_for_same_input() {
		let project = project();
		let landing = Utf8Path::new("/home/me/code/moon-landing/docker-compose.yml");
		let mounts = [mount("/home/me/code/moon-landing", "moon-landing")];
		let opts = ComposeRenderOptions {
			project: &project,
			dev_image: "moon-base:dev",
			bound_mounts: &mounts,
			include_files: &[landing],
		};
		let a = generate_compose(opts.clone());
		let b = generate_compose(opts);
		assert_eq!(a, b);
	}

	#[test]
	fn dev_image_override_lands_in_output() {
		// Once we publish, callers will pass the registry tag.
		let project = project();
		let render = generate_compose(ComposeRenderOptions {
			project: &project,
			dev_image: "huggingface/moon-base:0.1",
			bound_mounts: &[mount("/x", "x")],
			include_files: &[],
		});
		assert!(render.yaml.contains("image: huggingface/moon-base:0.1"));
	}

	#[test]
	fn project_name_lands_in_output() {
		let project = project_name_for_id("scratch").unwrap();
		let render = generate_compose(ComposeRenderOptions {
			project: &project,
			dev_image: "moon-base:dev",
			bound_mounts: &[],
			include_files: &[],
		});
		assert!(render.yaml.contains("name: moon-ws-scratch"));
	}
}
