// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What marks a terminal as agent-opened (ADR 0090): the label the
 * agent gave it and the command it launched it to run.
 */
export type AgentTerminal = { title: string, command: string, };
