// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppInfoMode } from "./AppInfoMode";

export type AppInfo = { 
/**
 * `"workspace"` when this process is bound to a real
 * workspace; `"preboot"` for the first-launch landing
 * process.
 */
mode: AppInfoMode, 
/**
 * Workspace slug this process owns. `None` in preboot
 * mode.
 */
workspaceId: string | null, 
/**
 * Human-readable workspace name from the catalog.
 * `None` in preboot mode and as a defensive fallback
 * when the catalog and the CLI arg disagree.
 */
workspaceName: string | null, };
