// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlackAppState } from "./SlackAppState";
import type { ThemeMode } from "./ThemeMode";
import type { WorkspaceSession } from "./WorkspaceSession";

export type AppState = { 
/**
 * What was on screen at the last successful save: workspace, tabs,
 * active pane. Restored verbatim on next launch when the workspace
 * folder still exists.
 */
last_session: WorkspaceSession | null, 
/**
 * Active UI theme. Per-machine; survives workspace switches.
 */
theme: ThemeMode, 
/**
 * Per-machine, non-secret Slack panel state. The `xoxp-` token
 * itself never lives here — it stays in the OS keyring (see
 * `specs/slack-chat.md`).
 */
slack: SlackAppState, };
