// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemeMode } from "./ThemeMode";
import type { WorkspaceSession } from "./WorkspaceSession";

export type AppState = { 
/**
 * What was on screen at the last successful save: workspace, tabs,
 * active pane. Restored verbatim on next launch when the workspace
 * folder still exists.
 */
last_session: WorkspaceSession | null, 
/**
 * Active UI theme. Per-machine; survives workspace switches.
 */
theme: ThemeMode, };
