// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bottom-panel slice of [`AppState`].
 *
 * Only chrome (visibility + height) lives here. Tab contents are
 * deliberately not persisted in `AppState`: log streams are tied to
 * running `docker compose logs -f` processes that don't survive a
 * launch, and **terminal** restore recipes are per-*workspace* — a
 * `container` terminal names `moon-ws-<id>-dev-1` and each folder
 * belongs to one workspace's bound set — so they live in the
 * per-workspace `session.json` (`WorkspaceSession::terminals`), not
 * in this machine-global file. Putting them here leaked workspace
 * A's terminals into workspace B.
 */
export type BottomPanelAppState = { 
/**
 * Whether the bottom panel was open at last shutdown. Defaults to
 * `false` — first-run users shouldn't have an empty panel
 * occupying screen real estate before they ask for it.
 */
visible: boolean, 
/**
 * Panel height in CSS pixels. Clamped to a sane range on the
 * frontend so a saved 0 / huge value can't render the editor
 * invisible.
 */
height: number, };
