// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bottom-panel slice of [`AppState`].
 *
 * Tab contents (open log streams, terminal sessions) are intentionally
 * not persisted: they're tied to running `docker compose logs -f`
 * processes that don't survive a launch, and re-spawning them blindly
 * on startup would surprise the user. Visibility + height are pure
 * chrome and safe to restore.
 */
export type BottomPanelAppState = { 
/**
 * Whether the bottom panel was open at last shutdown. Defaults to
 * `false` — first-run users shouldn't have an empty panel
 * occupying screen real estate before they ask for it.
 */
visible: boolean, 
/**
 * Panel height in CSS pixels. Clamped to a sane range on the
 * frontend so a saved 0 / huge value can't render the editor
 * invisible.
 */
height: number, };
