// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersistedTerminal } from "./PersistedTerminal";

/**
 * Bottom-panel slice of [`AppState`].
 *
 * Log-stream and diagnostics tabs are intentionally not persisted:
 * they're tied to running `docker compose logs -f` processes that
 * don't survive a launch. **Terminal tabs are** — not the PTY (the
 * process is gone with the IDE) but the recipe: target, owning
 * folder, and the shell-history line the terminal last ran. On
 * launch the frontend re-spawns each persisted terminal as a fresh
 * shell and replays `command` into it, so "relaunch the IDE, get my
 * three dev servers back" costs zero retyping. The recorded command
 * is *sourced from the shell's own history*, so a follow-up up-arrow
 * in the restored shell keeps walking the same session's history.
 */
export type BottomPanelAppState = { 
/**
 * Whether the bottom panel was open at last shutdown. Defaults to
 * `false` — first-run users shouldn't have an empty panel
 * occupying screen real estate before they ask for it.
 */
visible: boolean, 
/**
 * Panel height in CSS pixels. Clamped to a sane range on the
 * frontend so a saved 0 / huge value can't render the editor
 * invisible.
 */
height: number, 
/**
 * Terminal tabs to re-spawn on next launch, in tab order. Empty
 * on first run and whenever the last shutdown had no terminals
 * open — an empty list falls back to the "one default terminal"
 * auto-spawn in `WorkspaceState.restoreAppState`.
 */
terminals: Array<PersistedTerminal>, };
