// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Argument for `branch_switch`. `Local` runs `git switch
 * <name>`; `Pr` runs `gh pr checkout <number>` so cross-fork
 * PRs work without manual remote / fetch fiddling.
 */
export type BranchSwitchTarget = { "kind": "local", name: string, } | { "kind": "pr", number: number, };
