// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchListEntry } from "./BranchListEntry";
import type { PrListStatus } from "./PrListStatus";

/**
 * Result of `branch_list`. Three slots so the frontend can paint
 * local rows immediately even if the gh probe is slow / failing
 * — local always returns from `git for-each-ref` in single-digit
 * milliseconds, gh can stall on a network round-trip.
 */
export type BranchList = { 
/**
 * Recent local branches, newest committer-date first,
 * capped at a small number (today's slice ships 20 — bumps
 * when a real project hits the cap).
 */
local: Array<BranchListEntry>, 
/**
 * Open GitHub PRs against the active folder's repo. Empty
 * when [`pr_status`](Self::pr_status) is anything other
 * than `Ok`; capped at 30. Sub-filters (`@me`, "review
 * requested") are deferred — type-to-filter handles the
 * volume the team currently sees.
 */
prs: Array<BranchListEntry>, 
/**
 * Why `prs` is empty, if it is. `Ok` means "the section is
 * populated with whatever gh returned, including the empty
 * case of no open PRs" — the frontend distinguishes
 * "section unavailable" from "section truthfully empty".
 */
prStatus: PrListStatus, };
