// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One open browser tab. `url` is what was last asked for (by the
 * user's URL bar or an agent), not wherever in-page navigation has
 * since taken the iframe — that's cross-origin and invisible.
 */
export type BrowserTab = { id: number, url: string, 
/**
 * Resolve the URL inside the workspace shell container (through
 * a loopback tunnel) rather than on the host.
 */
in_container: boolean, };
