// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserTab } from "./BrowserTab";

/**
 * Payload of the `browser:tabs` event: the full tab set after a
 * change, plus which tab (if any) should be brought to front and
 * which should be reloaded.
 */
export type BrowserTabsChanged = { tabs: Array<BrowserTab>, focus: number | null, reload: number | null, };
