// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload of the `browser:page_request` event: the coder wants the
 * page bridge in tab `tab_id` to run `op` (ADR 0088). The frontend
 * relays it into the tab's iframe and answers with
 * `browser_page_respond(request_id, …)`.
 */
export type BrowserPageRequest = { request_id: number, tab_id: number, op: string, args: unknown, };
