// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One user-added OpenAI-compatible provider — OpenRouter, a local
 * llama.cpp / vLLM / Ollama, a hosted Anthropic-via-proxy, …
 * Persisted into [`crate::app_state::CoderAppState::providers`];
 * the API key lives in the OS keyring under
 * `service=moon-ide`, `account=coder-provider:<id>` and is never
 * surfaced in this struct — only the [`has_api_key`] flag is.
 *
 * `id` is opaque and assigned by the backend on
 * `coder_add_provider`. The picker addresses providers by id
 * across read / write / delete; `label` is a free-form human name
 * the user picked.
 *
 * [`has_api_key`]: Self::has_api_key
 */
export type CoderProviderConfig = { id: string, label: string, 
/**
 * OpenAI-compat `/v1` root, e.g.
 * `https://openrouter.ai/api/v1` or
 * `http://localhost:8080/v1`. Stored verbatim; the runner
 * builds request URLs by appending `/chat/completions` etc.
 */
base_url: string, 
/**
 * Per-provider standard model slug. Same wire shape as the
 * HF `standard_model` — empty string falls back to the
 * hardcoded default at request time.
 */
standard_model: string, 
/**
 * Per-provider cheap model slug. Same semantics as
 * [`standard_model`](Self::standard_model).
 */
cheap_model: string, 
/**
 * `true` iff the keyring currently holds an entry for this
 * provider. Server-set, read-only on the picker's side —
 * editing the key goes through `coder_set_provider_api_key`.
 * Deserialised as `false` when the field is missing so
 * inbound shapes from the frontend don't have to set it.
 */
has_api_key: boolean, };
