// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoderProviderConfig } from "./CoderProviderConfig";

/**
 * Read/write payload for `coder_get_model_settings` /
 * `coder_set_model_settings`.
 *
 * Mirrors the [`crate::app_state::CoderAppState`] subset the
 * picker cares about. The runner reads `standard_model` /
 * `cheap_model` / `bill_to` straight from
 * [`moon_coder::CoderModels`] (kept in sync on every write); slugs
 * are already in their final `model:provider` form by the time they
 * get here because the picker concatenates on click.
 *
 * **Active provider** is `None` for the implicit HF route (the
 * `standard_model` / `cheap_model` / `bill_to` fields apply only
 * in that case), or `Some(id)` matching one of the [`providers`]
 * entries — in which case the runner reads the picks off that
 * provider's record instead. User providers don't have a
 * `bill_to`; the HF-specific header is suppressed off the wire when
 * active.
 *
 * [`providers`]: Self::providers
 */
export type CoderModelSettings = { standard_model: string, cheap_model: string, bill_to: string, active_provider?: string | null, providers: Array<CoderProviderConfig>, 
/**
 * Per-slug context-window caps in tokens. See
 * [`crate::app_state::CoderAppState::context_window_overrides`]
 * for the wire-shape rationale; this field round-trips the
 * same map through the picker so the user can edit the cap
 * next to the model field.
 *
 * Slug is the full wire id used at the call site (with any
 * `:provider` suffix for HF, bare id for user providers).
 * `None` / missing entry = use the model's catalog window
 * directly. The runner clamps to `min(catalog, cap)` at
 * every [`moon_coder::CoderModels::context_window`] call
 * site so the usage ring + auto-compaction respect the cap
 * the same way they respect the actual window.
 */
context_window_overrides: { [key in string]: number }, };
