// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerConfig } from "./McpServerConfig";

/**
 * Per-workspace MCP state, persisted on
 * [`crate::session::WorkspaceSession`]. Per-workspace by design:
 * enabling playwright is a statement about one project's testing
 * needs, not a global preference, and custom servers are usually
 * project-specific.
 */
export type CoderMcpWorkspaceConfig = { 
/**
 * Ids (preset or custom) enabled for this workspace. Empty =
 * the meta-tools aren't advertised at all.
 */
enabled: Array<string>, 
/**
 * User-defined servers for this workspace.
 */
custom: Array<McpServerConfig>, };
