// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coder-specific slice of [`AppState`].
 *
 * Only frontend-side affordance pointers — the actual session
 * content lives under each workspace folder at
 * `<folder>/.moon/agent-sessions/<id>.jsonl`, not here.
 */
export type CoderAppState = { 
/**
 * Last-opened session id **per workspace folder**. Restored on
 * launch when the user revisits a folder: the active folder's
 * entry decides which session the panel mounts. Per the
 * multi-session design, every project gets its own slot so a
 * re-open of folder X resumes X's last session even if the
 * user has worked in folder Y in between. Cleared per-folder
 * when the matching session gets deleted; an `open_session`
 * call updates that folder's entry.
 */
last_session_by_folder: { [key in string]: string }, };
