// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coder-specific slice of [`AppState`].
 *
 * Only frontend-side affordance pointers — the actual session
 * content lives under
 * `<XDG_DATA_HOME>/moon-ide/coder-sessions/<project-slug>/<id>.jsonl`,
 * not here. See [`crate::session`] / `crates/moon-coder/src/sessions.rs`
 * for the on-disk format.
 */
export type CoderAppState = { 
/**
 * Last-opened session id **per workspace folder**. Restored on
 * launch when the user revisits a folder: the active folder's
 * entry decides which session the panel mounts. Per the
 * multi-session design, every project gets its own slot so a
 * re-open of folder X resumes X's last session even if the
 * user has worked in folder Y in between. Cleared per-folder
 * when the matching session gets deleted; an `open_session`
 * call updates that folder's entry.
 */
last_session_by_folder: { [key in string]: string }, 
/**
 * Slug of the "standard" model driving the main agent loop +
 * every sub-agent. Empty means "use the hardcoded default"
 * (`DEFAULT_STANDARD_MODEL` in `crates/moon-coder/src/defaults.rs`).
 * Format mirrors what the HF Inference Providers router accepts
 * in the request body — bare `Qwen/Qwen3.5-397B-A17B`, or
 * suffixed with `:scaleway` / `:fastest` / etc.
 */
standard_model: string, 
/**
 * Slug of the "cheap" model used for auto-rename, branch-name
 * suggester, commit-message suggester, compaction summary, and
 * folder-summary onboarding. Same format as `standard_model`.
 * Empty = `DEFAULT_CHEAP_MODEL`.
 */
cheap_model: string, 
/**
 * Organisation slug to send as the `X-HF-Bill-To` header on every
 * inference call. Empty = bill the user's personal account.
 * The user must be a paying member of the org and the org must
 * have inference credits, otherwise the router rejects the
 * request — we surface the router's error verbatim.
 */
bill_to: string, };
