// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of [`collect_paths`](crate) and `collect_paths_under`:
 * the enumerated path set plus the directories whose recursion
 * the depth cap stopped short of. The frontend treats
 * `depth_capped` like the gitignored-collapsed set, marking each
 * entry as lazy so a later expansion fetches its children on
 * demand. Empty `depth_capped` means the walk reached every leaf
 * without hitting the cap.
 */
export type CollectPathsResult = { paths: Array<string>, depth_capped: Array<string>, };
