// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the recent-commit list the SCM panel renders below the
 * sync buttons. Keeps the shape minimal — the panel needs enough to
 * identify each commit (short SHA, subject, author, relative date)
 * without turning into a full `git log` viewer. A click on a row opens
 * the diff view for that commit against its first parent.
 */
export type CommitEntry = { 
/**
 * First seven characters of the commit's SHA.
 */
shortSha: string, 
/**
 * Full 40-character SHA. Used as the diff endpoint when the user
 * clicks a row — `git diff <parent>..<sha>` needs the full hash.
 */
sha: string, 
/**
 * First line of the commit message.
 */
subject: string, 
/**
 * Full author name as recorded on the commit.
 */
author: string, 
/**
 * Relative date string from `git log --date=relative` — e.g.
 * `"2 hours ago"`. Pre-formatted by git so the frontend renders
 * it verbatim without a date library.
 */
dateRelative: string, };
