// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitStatusEntry } from "./GitStatusEntry";

/**
 * File-level changes for a single commit, returned by
 * `git_commit_diff`. The frontend opens a `commit://<sha>` pseudo-tab
 * whose sections read the base side from `parent_sha` and the after
 * side from the commit's own SHA — both via the existing
 * `git_ref_content` command, which already accepts any 40-char hex rev.
 */
export type CommitDiff = { 
/**
 * Full 40-char SHA of the commit's first parent. The frontend
 * passes this to `git_ref_content` for each section's base side.
 * Empty string when the commit has no parent (root commit) — the
 * base side renders empty and every file reads as a pure addition.
 */
parentSha: string, 
/**
 * Full 40-char SHA of the commit itself. The frontend passes this
 * to `git_ref_content` for each section's after side.
 */
commitSha: string, 
/**
 * First line of the commit message. Shown in the commit view's
 * banner alongside the short SHA.
 */
subject: string, 
/**
 * File-level changes from `parent_sha` to `commit_sha`, parsed
 * with the same `--name-status -z --no-renames` discipline as
 * `BranchDiffStatus`.
 */
entries: Array<GitStatusEntry>, };
