// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which baseline the SCM machinery (status entries, change
 * gutter, diff view) compares the working tree against. `Head`
 * is the regular `git status` against `HEAD`. `Default`
 * substitutes the merge-base with the default branch
 * (`origin/main` / `origin/master`), so the file tree, gutter,
 * and diff view all surface "what does this branch / PR change
 * relative to main" instead of "what's modified since my last
 * commit".
 *
 * Persisted per folder in [`crate::session::FolderSession`]:
 * flipping a busy monorepo into `Default` shouldn't drag a
 * sleepy side-project's SCM panel along with it. `Default`
 * silently degrades to `Head` when there's no resolvable
 * default branch, no merge-base, or HEAD is sitting on the
 * default branch itself — in those states the toggle still
 * renders but the underlying view is identical to `Head`.
 */
export type CompareBaseline = "head" | "default";
