// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentSearchOptions = { query: string, case_sensitive: boolean, regex: boolean, 
/**
 * Cap to keep the UI responsive. The first `max_matches` matches are
 * returned and the rest is reported back via `truncated = true`.
 */
max_matches: number, };
