// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerStatus } from "./ContainerStatus";

/**
 * Payload of the `container:state` Tauri event, broadcast after
 * every lifecycle command (and, eventually, from the docker
 * events watcher 2.2 will add).
 *
 * `workspace_id` is included so the frontend can route the
 * event to the right workspace once multi-window arrives — for
 * 2.0 it always matches the active workspace.
 */
export type ContainerStateChange = { workspace_id: string, status: ContainerStatus, };
