// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * High-level state of the workspace's compose project.
 *
 * Drives the status-pip glyph and the "Set up" / "Pause" /
 * "Resume" affordances. Callers should treat any unknown
 * variant as `Failed` rather than `Running` — see
 * `crates/moon-container/src/lifecycle.rs#aggregate_state`.
 */
export type ContainerState = "absent" | "creating" | "running" | "paused" | "stopped" | "failed";
