// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentSearchOptions = { query: string, case_sensitive: boolean, regex: boolean, 
/**
 * Cap to keep the UI responsive. The first `max_matches` matches are returned.
 */
max_matches: number, 
/**
 * Cap on number of lines of context per match.
 */
max_files: number, };
