// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentSearchHit } from "./ContentSearchHit";

export type ContentSearchResult = { hits: Array<ContentSearchHit>, 
/**
 * True when we hit `max_matches` and stopped early.
 */
truncated: boolean, };
