// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerStatus } from "./ContainerStatus";

/**
 * Payload of the `container:state` Tauri event, broadcast after
 * every lifecycle command (and, eventually, from the docker
 * events watcher 2.2 will add). Phase 7 made each window one
 * process bound to one workspace, so the event implicitly
 * scopes to that process — no `workspace_id` field needed.
 */
export type ContainerStateChange = { status: ContainerStatus, };
