// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mass-replace request. Reuses the same matcher shape as
 * [`ContentSearchOptions`] (`query` + `case_sensitive` + `regex` +
 * `whole_word` + `include_glob`) so the "preview matches, then
 * replace" UX in the search palette renders consistent counts.
 * `replacement` is interpreted verbatim in plain-text mode and as
 * a regex replacement template (`$1` / `${name}` / `$$` for a
 * literal `$`) in regex mode, matching what `Regex::replace_all`
 * understands. No `max_matches` cap: replace runs to completion
 * across every matched file or fails the whole batch.
 */
export type ContentReplaceOptions = { query: string, replacement: string, case_sensitive: boolean, regex: boolean, whole_word: boolean, include_glob: string | null, };
