// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentSearchHit = { path: string, line: bigint, column: bigint, line_text: string, 
/**
 * Range of the matched text within `line_text` (UTF-8 byte offsets).
 */
match_start: number, match_end: number, };
