// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentReplaceError } from "./ContentReplaceError";

/**
 * Summary of a completed mass-replace. `files_changed` is the
 * number of files whose bytes actually differ post-replace
 * (a file that matched but produced identical bytes — e.g. the
 * replacement equals the matched text — is not counted). Files
 * the walker visited but couldn't read / write get one entry per
 * path in `errors`; the batch keeps going past per-file failures
 * so a single permission denial doesn't strand the rest of the
 * replacements.
 */
export type ContentReplaceResult = { files_changed: number, replacements: number, errors: Array<ContentReplaceError>, };
