// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerState } from "./ContainerState";
import type { ServiceStatus } from "./ServiceStatus";

/**
 * Snapshot returned by `container_status` and embedded in
 * every [`ContainerStateChange`] event.
 */
export type ContainerStatus = { state: ContainerState, services: Array<ServiceStatus>, };
