// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryKind } from "./EntryKind";

export type DirEntry = { name: string, path: string, kind: EntryKind, 
/**
 * Size in bytes for files. None for directories or when stat is skipped.
 */
size: bigint | null, 
/**
 * Modification time as Unix milliseconds. None when stat is skipped.
 */
mtime_ms: bigint | null, is_hidden: boolean, };
