// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndOfLine } from "./EndOfLine";
import type { IndentStyle } from "./IndentStyle";

/**
 * Fully resolved editorconfig for one file. Defaults reflect moon-ide
 * house style (tabs at width 2, lf, trim trailing whitespace, final
 * newline) — when no `.editorconfig` is present these are what the
 * editor and the pre-save pipeline use. The defaults match what oxfmt /
 * prettier / rustfmt produce for this repo, so typing in moon-ide-on-
 * moon-ide stays consistent until the format hook fires.
 */
export type EditorConfig = { indent_style: IndentStyle, indent_size: number, tab_width: number, end_of_line: EndOfLine | null, insert_final_newline: boolean, trim_trailing_whitespace: boolean, charset: string, max_line_length: number | null, };
