// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileSearchResult = { path: string, 
/**
 * Match score, higher is better. Used purely for ordering.
 */
score: bigint, };
