// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a folder is bound into the workspace. Drives how the folder
 * bar renders it and what happens when it's removed.
 */
export type FolderOrigin = { "kind": "user_picked" } | { "kind": "worktree", 
/**
 * Absolute path of the parent folder the worktree was
 * branched from — the folder bar nests under it.
 */
parentPath: string, 
/**
 * Branch the worktree is checked out on. The folder bar
 * shows this as the row's label.
 */
branch: string, };
