// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrListScope } from "./PrListScope";
import type { SplitSide } from "./SplitSide";

/**
 * One folder's slice of UI state. Multiple of these live inside a
 * [`WorkspaceSession`] — the user's tabs/active-pane state is per
 * folder, swapping when the active bar changes. Phase 2.5 ships
 * multi-folder UX; before that, this list always had exactly one
 * entry but the wire shape stays the same.
 */
export type FolderSession = { 
/**
 * Absolute path of the folder on the host. Used to re-bind the
 * folder on next launch and to invalidate stale entries when the
 * user opens a different folder.
 */
folder_path: string, 
/**
 * Tabs open in the left pane, in tab order. May reference files
 * that no longer exist; the frontend filters those out at restore
 * time.
 */
open_files_left: Array<string>, 
/**
 * Tabs open in the right pane, in tab order. Empty when no split
 * is active. The two lists are independent — a file can live in
 * one pane, both, or neither (VSCode/Zed convention).
 */
open_files_right: Array<string>, 
/**
 * Active tab on the left pane, if any. Must appear in `open_files_left`.
 */
active_left: string | null, 
/**
 * Active tab on the right pane, if any. `None` when the split is
 * closed; `Some` only makes sense alongside `has_split = true`.
 */
active_right: string | null, has_split: boolean, focused_side: SplitSide, 
/**
 * Branch-switcher PR-section filter for this folder. Persisted
 * per folder so flipping to "Participating" on a busy
 * monorepo doesn't drag a sleepy side-project's palette into
 * participating-only mode too. Defaults to
 * [`PrListScope::All`] for fresh sessions and for sessions
 * written by older builds (`#[serde(default)]`).
 */
pr_scope: PrListScope, };
