// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-port live state, as reported by `ports_status`.
 *
 * The panel renders one of these per declared forward; the dot
 * next to each row is keyed off the variant.
 */
export type ForwardedPortHealth = "live" | "host_port_busy" | "proxy_down";
