// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One declared forward from the host to the dev container.
 *
 * `host_port` defaults to `container_port` on the picker; the
 * user only edits it when two workspaces want the same dev-side
 * port and need to disambiguate on the host (workspace A:
 * `3000 -> 3000`, workspace B: `3001 -> 3000`).
 *
 * Loopback-only: the proxy sidecar binds `127.0.0.1:host_port`
 * on the host. We deliberately don't expose a `0.0.0.0` toggle
 * yet — per AGENTS.md "hardcode first, configure later", that
 * lands when somebody actually wants to reach a workspace dev
 * server from another device.
 */
export type ForwardedPort = { 
/**
 * Port the user's process listens on **inside** the dev
 * container. The proxy sidecar opens
 * `tcp:moon-ws-<id>-dev-1:<container_port>` on each accepted
 * host-side connection.
 */
container_port: number, 
/**
 * Port the proxy sidecar publishes on the host
 * (`127.0.0.1:host_port`). Defaults to `container_port` on
 * the picker; the user re-types it on conflict.
 */
host_port: number, 
/**
 * Free-form human label (`"vite"`, `"api"`, …). Surfaced in
 * the Ports panel; doesn't affect the wire shape and may be
 * empty for forwards the user didn't bother naming.
 */
label: string, };
