// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForwardedPort } from "./ForwardedPort";
import type { ForwardedPortHealth } from "./ForwardedPortHealth";

/**
 * One row of `ports_status` output: the user-facing forward
 * definition plus its current health.
 */
export type ForwardedPortStatus = { forward: ForwardedPort, health: ForwardedPortHealth, };
