// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsEventKind } from "./FsEventKind";

export type FsEvent = { subscription_id: string, kind: FsEventKind, path: string, };
