// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight info the SCM panel renders next to its commit
 * input: the active branch name, a short HEAD hash for the
 * detached state, and ahead/behind counts vs the upstream.
 * `None` (for the strings) and `0` (for the counts) are the
 * "this signal isn't available right now" fallbacks; the panel
 * renders the empty case as an inert label rather than a hard
 * error.
 */
export type GitBranchInfo = { 
/**
 * Branch name, e.g. `"main"`. `None` when HEAD is detached,
 * the folder isn't a git repo, or `git` itself isn't on PATH —
 * the SCM panel falls back to `head_short_sha` for the
 * detached case and to a plain "no branch" label otherwise.
 */
name: string | null, 
/**
 * First seven characters of the HEAD commit's SHA. `None` when
 * the repo has no commits yet (a fresh `git init`), HEAD is
 * unreadable, or the folder isn't a git repo.
 */
headShortSha: string | null, 
/**
 * Whether the current branch has a configured upstream
 * (`branch.<name>.remote` + `branch.<name>.merge`). `false`
 * when the branch was just created locally and never pushed,
 * when HEAD is detached, when the folder isn't a git repo,
 * and when the branch's upstream is configured but currently
 * unreachable. Distinguishes "in sync with upstream" (push +
 * pull are no-ops, `ahead == behind == 0`, `has_upstream ==
 * true`) from "no upstream yet" (the SCM panel renders a
 * "Publish branch" affordance instead of the sync button).
 */
hasUpstream: boolean, 
/**
 * Number of commits the local branch has that its configured
 * upstream doesn't — commits that would be sent on the next
 * `git push`. `0` when there's no upstream configured, no
 * HEAD, or the count couldn't be determined.
 */
ahead: number, 
/**
 * Number of commits the upstream has that the local branch
 * doesn't — commits that would be merged in on the next
 * `git pull`. Same `0`-fallback semantics as `ahead`.
 */
behind: number, 
/**
 * Pre-built URL for opening a pull request against the
 * repo's primary remote. `Some` only when the remote is a
 * recognised host (currently `github.com`), HEAD is on a
 * named branch (not detached), and the branch name has
 * successfully URL-escaped. The SCM panel still gates the
 * "Open PR" button on UI policy (non-main / non-master,
 * `has_upstream`); the backend just produces the URL when
 * it has the inputs.
 */
prUrl: string | null, };
