// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitBaseCheckFile } from "./GitBaseCheckFile";

/**
 * How far a branch has drifted behind the repo's default branch,
 * plus the files its diff touches — the coordinator's
 * rebase-before-merge / rebase-before-PR gate (ADR 0056).
 */
export type GitBaseCheck = { 
/**
 * The default-branch remote ref compared against, e.g.
 * `"origin/main"`.
 */
defaultBranchRemoteRef: string, 
/**
 * Commits the default branch has that `HEAD` doesn't
 * (`git rev-list --count HEAD..<ref>`). Non-zero means the
 * branch is based on a stale default.
 */
behindDefault: number, 
/**
 * Every path in `git diff <ref>...HEAD` (three-dot: the
 * branch's own changes relative to the merge-base) with
 * per-file addition/deletion counts.
 */
files: Array<GitBaseCheckFile>, };
