// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file in a branch's diff against the default branch
 * (`git diff <ref>...HEAD --numstat`). The coordinator's base
 * check cross-references these against the files a worker
 * actually touched: a path with `deletions > 0` the worker never
 * edited is the stale-base revert tripwire.
 */
export type GitBaseCheckFile = { 
/**
 * Workspace-relative path.
 */
path: string, 
/**
 * Lines added on the branch side of the three-dot diff.
 */
additions: number, 
/**
 * Lines deleted on the branch side of the three-dot diff.
 * Non-zero on a file the worker didn't write means the diff
 * reverts work that merged after the branch's base.
 */
deletions: number, };
