// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate change counts for a single bound folder. Drives the
 * per-folder badges on the project bar so a user can see at a
 * glance which folders an agent (or anything else) just modified
 * — even folders that aren't currently active. `Untracked` files
 * fold into `added` because the project bar's signal-to-noise is
 * "this folder has a new file in it"; the SCM panel inside the
 * active folder still distinguishes the two.
 */
export type GitChangeSummary = { added: number, modified: number, deleted: number, };
