// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of a successful `git_commit`. The SCM panel renders
 * `short_sha` + `summary` in the post-commit toast so the user
 * can verify the commit landed without opening a terminal.
 */
export type GitCommitResult = { 
/**
 * First seven characters of the new commit's SHA.
 */
shortSha: string, 
/**
 * First line of the commit message we just wrote, echoed back
 * for display. Same string the user typed (modulo trailing
 * whitespace), so callers don't have to round-trip it.
 */
summary: string, };
