// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-line blame: who last touched this line, when, and with what
 * commit. The inline current-line annotation uses `author_short` +
 * a frontend-computed relative date + `summary`; the hover tooltip
 * consumes the full set.
 */
export type GitLineBlame = { 
/**
 * 40-char commit hash, or 40 zero characters for a line that's
 * been edited locally but not yet committed. Frontend checks
 * for `is_uncommitted` rather than comparing the string.
 */
sha: string, 
/**
 * True iff `sha` is the all-zero "Not Committed Yet" sentinel
 * that `git blame` emits for local edits. Peeled out for the UI
 * so a "You, uncommitted" badge doesn't have to know the
 * convention.
 */
isUncommitted: boolean, 
/**
 * Full author name as recorded on the commit.
 */
author: string, 
/**
 * Author e-mail without the angle brackets `git blame` puts
 * around it. Frontend rarely shows this beyond the hover
 * tooltip; useful for gravatars / SCM-tool links later.
 */
authorEmail: string, 
/**
 * Unix timestamp (UTC seconds) of the commit's author-time
 * (not committer-time — blame tools universally prefer the
 * original authorship moment over a later rebase's stamp).
 */
authorTime: bigint, 
/**
 * First line of the commit message. Subjects run the gamut from
 * 10 to 200 chars; the widget renderer ellipsizes locally.
 */
summary: string, 
/**
 * Full commit message (subject + body, unwrapped). Rendered
 * verbatim in the hover tooltip with `white-space: pre-wrap`,
 * so line breaks survive. Markdown is intentionally *not*
 * interpreted — commit messages aren't meant to be rich text
 * and rendering them as Markdown would be surprising when e.g.
 * list-style bullets get chewed up.
 */
message: string, };
