// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileStatus } from "./GitFileStatus";

export type GitStatusEntry = { 
/**
 * Workspace-relative path, directories terminated with `/` to
 * match the `read_dir` and tree conventions. Deleted entries
 * never carry a trailing slash — git can only delete files, not
 * whole directories, in this representation.
 */
path: string, status: GitFileStatus, };
