// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Namespace summary returned by `coder_hub_list_namespaces`.
 * Populates the connect modal's dropdown with the user's login
 * and every org they belong to.
 */
export type HubNamespace = { "kind": "user", name: string, } | { "kind": "org", name: string, };
