// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One session that errored out during `coder_hub_upload_all_sessions`.
 */
export type HubUploadFailure = { session_id: string, error: string, };
