// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

/**
 * One line of diagnostic log output. `seq` is a process-wide
 * monotonically-increasing counter so the frontend can tell
 * "appended" from "back-fill" when it merges the snapshot returned
 * by `logs_snapshot` with the live stream from the `logs:entry`
 * event.
 */
export type LogEntry = { 
/**
 * Bucket key (see module docs). Free-form; the frontend uses
 * it as both grouping key and tab title.
 */
source: string, level: LogLevel, message: string, 
/**
 * Wall-clock unix epoch milliseconds at emit time.
 */
tsMs: bigint, 
/**
 * Monotonic per-process counter starting at 1.
 */
seq: bigint, };
