// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity tag attached to a [`LogEntry`]. Maps 1:1 to `tracing`'s
 * `Level` minus `TRACE`: noise that low never makes it into a
 * human-facing buffer.
 */
export type LogLevel = "debug" | "info" | "warn" | "error";
