// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single line of `docker compose logs` output streamed to the
 * frontend. Emitted on the `compose_logs:line` Tauri event;
 * the frontend buffers per `stream_id` so multiple log tabs
 * don't interleave.
 *
 * `channel` is `"stdout"` or `"stderr"` so the renderer can
 * colour them differently (compose itself only writes to
 * stdout for service output, but errors from the docker CLI
 * arrive on stderr — keeping them separated lets the UI
 * surface those distinctly).
 */
export type LogStreamLine = { stream_id: string, channel: string, text: string, };
