// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Final event for a log stream, fired exactly once when the
 * underlying `docker compose logs -f` child exits. `code` is
 * the process's exit code if we caught it, or `None` if the
 * supervisor was cancelled before it could observe the wait()
 * result. Either way the frontend should mark the tab as no
 * longer streaming and stop sending close calls for this id.
 */
export type LogStreamClosed = { stream_id: string, code: number | null, };
