// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspCompletionKind } from "./LspCompletionKind";

export type LspCompletionItem = { label: string, kind: LspCompletionKind | null, 
/**
 * Short right-hand annotation: signature summary, type name, etc.
 */
detail: string | null, 
/**
 * Longer markdown body shown in the selected-item side panel.
 */
documentation: string | null, 
/**
 * Text inserted if different from `label`. CM's autocomplete
 * uses `label` as the display text and falls back to it as the
 * insert text when this is `None`.
 */
insertText: string | null, 
/**
 * Sort key if the server wants a specific order — CM sorts by
 * `label` by default, which is sometimes worse (e.g. private
 * `_` members bubble to the top).
 */
sortText: string | null, 
/**
 * Filter key if the server wants a different match surface than
 * `label`. Same rationale as `sort_text`.
 */
filterText: string | null, };
