// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Subset of LSP's `CompletionItemKind`. We keep the full list rather
 * than folding (e.g.) `Struct` into `Class`: the UI uses the kind
 * only for iconography, and collapsing kinds would lose information
 * that's cheap to carry.
 */
export type LspCompletionKind = "text" | "method" | "function" | "constructor" | "field" | "variable" | "class" | "interface" | "module" | "property" | "unit" | "value" | "enum" | "keyword" | "snippet" | "color" | "file" | "reference" | "folder" | "enummember" | "constant" | "struct" | "event" | "operator" | "typeparameter";
