// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspCompletionItem } from "./LspCompletionItem";

export type LspCompletionList = { 
/**
 * `true` when the server truncated — CM should re-query on the
 * next keystroke rather than trust the current list as final.
 */
isIncomplete: boolean, items: Array<LspCompletionItem>, };
