// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspTextEdit } from "./LspTextEdit";

/**
 * All edits the server wants applied to a single document. `path`
 * is the same workspace-relative form the rest of the LSP surface
 * uses; edits that target files outside the active folder are
 * dropped at the translation boundary (we don't support cross-
 * workspace rename today).
 */
export type LspDocumentEdit = { path: string, edits: Array<LspTextEdit>, };
