// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspDiagnostic } from "./LspDiagnostic";

/**
 * Pushed on the `lsp:diagnostics` Tauri event whenever a server
 * emits `textDocument/publishDiagnostics`. `path` is the same
 * workspace-relative form the frontend opens files with; the
 * backend translates between that and `file://` URIs internally.
 */
export type LspDiagnosticsEvent = { path: string, diagnostics: Array<LspDiagnostic>, };
