// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspRange } from "./LspRange";
import type { LspSeverity } from "./LspSeverity";

export type LspDiagnostic = { range: LspRange, severity: LspSeverity, message: string, 
/**
 * Producer of the diagnostic, e.g. `"ts"`, `"typescript"`,
 * `"eslint"`. Rendered as a tag in the tooltip so a user facing
 * a "disagreement" between two tools can tell whose opinion is
 * on screen.
 */
source: string | null, 
/**
 * Rule / error code as a string. Some servers emit integers, some
 * emit strings — we stringify during translation so the frontend
 * can just `Display` it.
 */
code: string | null, };
