// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspFileChangeKind } from "./LspFileChangeKind";

/**
 * One path + its change kind, forwarded to
 * `lsp_notify_files_changed` so the broker can translate to
 * `FileChangeType` per event.
 */
export type LspFileChange = { 
/**
 * Workspace-relative, forward-slash separated.
 */
path: string, kind: LspFileChangeKind, };
