// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened to a file we're about to report to a language
 * server via `workspace/didChangeWatchedFiles`. Maps 1:1 onto
 * LSP's `FileChangeType` (Created=1, Changed=2, Deleted=3), but
 * lives here so the watcher → frontend → broker pipeline speaks
 * the moon protocol end to end instead of leaking raw LSP
 * numbers across the Tauri boundary.
 *
 * The distinction matters for correctness: a `git switch` deletes
 * files the new branch doesn't have and creates files it does.
 * Telling the server a deleted file merely "changed" makes it try
 * to re-read the file from disk, fail, and keep serving the
 * stale in-memory snapshot — exactly the "type updated in
 * another file but the LSP still shows the old errors" symptom.
 * With a real `deleted` kind the server drops the snapshot
 * instead.
 */
export type LspFileChangeKind = "created" | "changed" | "deleted";
