// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspRange } from "./LspRange";

/**
 * Response to a hover request. `contents` is pre-rendered Markdown
 * the UI can drop into a markdown-it instance; we normalise
 * `MarkedString` / `MarkupContent` / plaintext on the broker side so
 * the UI has one branch.
 */
export type LspHover = { contents: string, 
/**
 * Range covered by the hover, if the server provided one. CM
 * uses this to decide when to dismiss the tooltip as the caret
 * moves.
 */
range: LspRange | null, };
