// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspRange } from "./LspRange";

/**
 * Result of `textDocument/prepareRename`. `Some(...)` means the
 * server has confirmed the cursor sits on a renameable symbol
 * and hands back the existing identifier's range (so the
 * frontend can position its inline input) plus a placeholder
 * (typically the existing name; some servers strip a `$`
 * sigil or similar). `None` means "no rename here" — the
 * frontend flashes a quiet message.
 */
export type LspPrepareRename = { range: LspRange, placeholder: string, };
