// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-language server availability reported on the
 * `lsp:status` Tauri event. We emit on every transition so the
 * status bar can paint without polling.
 */
export type LspServerStatus = "notavailable" | "starting" | "running" | "crashed" | "stopped";
