// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspServerStatus } from "./LspServerStatus";

export type LspStatusEvent = { 
/**
 * Language id per LSP convention: `typescript`, `typescriptreact`,
 * `javascript`, `javascriptreact`, later `rust`, `svelte`, `css`,
 * etc. Stable across the protocol.
 */
languageId: string, status: LspServerStatus, 
/**
 * Short human-readable message for the status pill tooltip when
 * we have something to say (binary name, crash reason, etc.).
 */
detail: string | null, };
