// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspRange } from "./LspRange";

/**
 * One edit inside a single document. Range is the existing text
 * to replace; `new_text` is what to put in its place. Empty
 * `new_text` is a deletion. LSP guarantees edits inside a single
 * document's edit list never overlap, so a frontend applier can
 * sort by start position and run them right-to-left without
 * shifting offsets.
 */
export type LspTextEdit = { range: LspRange, newText: string, };
