// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspDocumentEdit } from "./LspDocumentEdit";

/**
 * Result of a `textDocument/rename` — the server's plan for
 * every file that needs to change. The frontend applies open-
 * buffer edits in memory (marking the file dirty) and writes
 * closed-file edits to disk through the workspace host, then
 * fires `workspace/didChangeWatchedFiles` so the server can
 * resync.
 *
 * `document_edits` is the only field — we deliberately skip the
 * `create / rename / delete` resource operations that LSP's
 * `WorkspaceEdit` can also carry. A pure-identifier rename
 * doesn't need them, and supporting file-system mutations
 * triggered by an LSP without a confirmation surface is a
 * trap.
 */
export type LspWorkspaceEdit = { documentEdits: Array<LspDocumentEdit>, };
