// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an MCP server process runs.
 */
export type McpRunTarget = "host" | "container";
