// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the settings UI's server list: a preset or custom
 * server plus its enabled state for the current workspace.
 */
export type McpServerStatus = { 
/**
 * `true` for hardcoded presets (not removable).
 */
preset: boolean, 
/**
 * Enabled for the current workspace.
 */
enabled: boolean, 
/**
 * Stable id — the preset's well-known name (`playwright`) or
 * an opaque `mcp-<unix-ms>` for custom entries.
 */
id: string, 
/**
 * Human label for the settings UI.
 */
label: string, 
/**
 * Executable to spawn (stdio transport only).
 */
command: string, 
/**
 * Arguments passed verbatim.
 */
args: Array<string>, 
/**
 * Extra environment for the server process, applied over the
 * spawn environment (host env for a host spawn, the
 * container's `docker exec` env otherwise). Empty for every
 * preset; custom servers use it for config the server reads
 * from env (`LD_LIBRARY_PATH`-style workarounds, tokens,
 * feature flags).
 */
env: { [key in string]: string }, 
/**
 * 1-2 sentences surfaced to the model in the meta-tool
 * descriptions so it knows when the server is worth a
 * `mcp_list_tools` round-trip.
 */
description: string, };
