// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One MCP server definition — either a hardcoded preset
 * (moon-coder's `mcp::preset_servers`) or a user-defined custom
 * entry persisted per workspace.
 *
 * Servers spawn via `docker exec` in the workspace shell
 * container — the same sandbox the coder's `bash` runs in — so
 * there is no per-server run-target knob. An early `runs:
 * host|container` field was removed before any server used the
 * host option; `#[serde(default)]` absorbs the key in existing
 * `session.json` files.
 */
export type McpServerConfig = { 
/**
 * Stable id — the preset's well-known name (`playwright`) or
 * an opaque `mcp-<unix-ms>` for custom entries.
 */
id: string, 
/**
 * Human label for the settings UI.
 */
label: string, 
/**
 * Executable to spawn (stdio transport only).
 */
command: string, 
/**
 * Arguments passed verbatim.
 */
args: Array<string>, 
/**
 * Extra environment for the server process, applied over the
 * spawn environment (host env for a host spawn, the
 * container's `docker exec` env otherwise). Empty for every
 * preset; custom servers use it for config the server reads
 * from env (`LD_LIBRARY_PATH`-style workarounds, tokens,
 * feature flags).
 */
env: { [key in string]: string }, 
/**
 * 1-2 sentences surfaced to the model in the meta-tool
 * descriptions so it knows when the server is worth a
 * `mcp_list_tools` round-trip.
 */
description: string, };
