// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All protocol errors share this shape so the UI can render them uniformly.
 */
export type MoonError = { "code": "NotFound", "message": string } | { "code": "IoError", "message": string } | { "code": "PermissionDenied", "message": string } | { "code": "HostUnavailable", "message": string } | { "code": "InvalidArgument", "message": string } | { "code": "Internal", "message": string };
