// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NextEditProbeKind } from "./NextEditProbeKind";

export type NextEditProbeResult = { kind: NextEditProbeKind, detail: string | null, };
