// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NextEditCompleteParams = { baseUrl: string, 
/**
 * Path relative to the active workspace folder, forward slashes.
 */
relativePath: string, 
/**
 * Zero-based line index of the caret line.
 */
cursorLine: number, documentText: string, 
/**
 * `git show HEAD:<path>` text when available; feeds the `original` window.
 */
headText: string | null, };
