// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NextEditCompleteResult = { 
/**
 * Predicted text for the edited line range (newline-separated).
 */
replacement: string, from_line: number, to_line: number, };
