// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NextEditServerSnapshot = { running: boolean, pid: number | null, lastExitCode: number | null, startError: string | null, logTail: Array<string>, };
