// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Managed `llama-server` spawn settings plus an optional HTTP override when the user runs the server themselves.
 */
export type NextEditAppState = { 
/**
 * When non-empty, probes and completion use this URL instead of `http://{server_host}:{server_port}`.
 */
external_base_url?: string, 
/**
 * Executable name (`llama-server`) or absolute path to the binary.
 */
llama_binary: string, 
/**
 * Hugging Face repo for `--hf-repo` (e.g. `sweepai/sweep-next-edit-1.5B` or `org/repo:Q4_K_M`).
 */
hf_repo: string, server_host: string, server_port: number, 
/**
 * Managed mode only: start `llama-server` on IDE launch. Cleared when the user stops from the UI.
 */
server_autostart: boolean, };
