// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OpenRouter credit status for a configured provider key.
 * Combined result of `GET /key` (per-key usage / optional spend
 * cap) and `GET /credits` (account balance) so the picker
 * renders both with one round trip. Both endpoints authenticate
 * with the inference key itself — no provisioning key needed.
 * All figures are US dollars.
 */
export type OpenRouterCredits = { 
/**
 * Account-level: total credits ever purchased (`/credits`).
 */
total_credits: number, 
/**
 * Account-level: total spend across the account (`/credits`).
 * Remaining balance = `total_credits - total_usage`.
 */
total_usage: number, 
/**
 * Lifetime spend attributed to the current key (`/key`).
 */
key_usage: number, 
/**
 * Optional per-key spend cap. `None` = uncapped (the common
 * case) — the key draws on the account balance directly.
 */
key_limit?: number | null, 
/**
 * Headroom left under the per-key cap. `None` when uncapped.
 */
key_limit_remaining?: number | null, 
/**
 * `true` for keys on OpenRouter's free tier (stricter rate
 * limits; the picker renders a small flag).
 */
is_free_tier: boolean, };
