// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalTarget } from "./TerminalTarget";

/**
 * One terminal tab's restore recipe. See
 * [`WorkspaceSession::terminals`].
 */
export type PersistedTerminal = { 
/**
 * Where the shell runs (host + cwd, or container + cwd) — fixed
 * at open time, same identity the live tab carries.
 */
target: TerminalTarget, 
/**
 * Bound folder the terminal was opened for (host path), or
 * `None` for a folder-less `$HOME` shell. Recorded so the
 * restored terminal registers under the same project for the
 * coder's `list_terminals` / `read_terminal` tools (ADR 0048).
 */
folder: string | null, 
/**
 * The shell-history line recorded for this terminal — what the
 * user would get from one up-arrow in that shell. Prefilled at
 * the restored shell's prompt (not executed). `None` when
 * nothing was ever run.
 */
command: string | null, };
