// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForwardedPort } from "./ForwardedPort";

/**
 * Result of `ports_set`. Returned synchronously so the picker
 * can show "applied" vs "host port busy on these N entries"
 * without a round-trip through the event bus.
 *
 * On success (`conflicts` empty) the forward set on disk and
 * the running sidecar both reflect `applied`. On a partial
 * conflict (one or more of the requested host ports were busy
 * before the sidecar could bind them) we still persist the
 * requested set — the user's intent is recorded for the next
 * retry — but flag the conflicting entries here so the picker
 * can render them with a red dot and a "host port busy" tooltip.
 * The non-conflicting entries do come up in the same sidecar
 * run.
 */
export type PortsApplyResult = { applied: Array<ForwardedPort>, conflicts: Array<ForwardedPort>, };
