// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the PR section of [`BranchList`] is empty. Surfaced in the
 * palette as the section's empty-state row so the user knows
 * whether to install gh, run `gh auth login` / `fj auth login`,
 * or accept that their remote isn't on a supported forge.
 */
export type PrListStatus = { "kind": "ok" } | { "kind": "gh_missing" } | { "kind": "gh_not_authed" } | { "kind": "unsupported_remote" } | { "kind": "failed", detail: string, };
