// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scope filter for `branch_list`'s PR section. `All` mirrors
 * `gh pr list --state open` (every open PR in the repo);
 * `Participating` uses GitHub's search qualifiers to keep only
 * PRs the user is involved in — a focused list for repos with
 * dozens of in-flight changes.
 *
 * "Participating" runs two `gh pr list --search` queries in
 * parallel and merges them by PR number:
 *
 * - `state:open involves:@me` — author, assignee, mentioned, or
 *   commenter (everything GitHub's notification "Participating"
 *   filter covers).
 * - `state:open review-requested:@me` — review explicitly
 *   requested from the user. Not covered by `involves:`.
 *
 * The default (`All`) matches the previous slice's behaviour so
 * flipping the toggle in the palette is the gesture, not the
 * other way around.
 */
export type PrListScope = "all" | "participating";
