// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectComposeStatus } from "./ProjectComposeStatus";

/**
 * Payload of the `project_compose:state` Tauri event,
 * broadcast after every per-folder lifecycle mutation. Keyed
 * on `folder_path` so the UI can update one folder bar without
 * re-querying the others.
 */
export type ProjectComposeStateChange = { workspace_id: string, folder_path: string, project: ProjectComposeStatus, };
