// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a `coder_probe_provider` call. Returned on the
 * `Add provider` modal's verify gesture so the user can confirm
 * the URL + key combination actually reaches a sane endpoint
 * before saving. Failures land as `MoonError`; this success
 * shape only carries advisory info (model count, optional
 * `id`-shaped names) the picker shows inline.
 */
export type ProviderProbeResult = { 
/**
 * Number of model entries the probe returned. `0` is
 * possible (well-formed `/v1/models` with an empty list,
 * or a 1-token completion fallback that gives no catalog
 * info). Picker uses this just to render a confirmation
 * blurb.
 */
model_count: number, 
/**
 * First few model ids the probe surfaced, capped at a
 * handful for UI breathability. Empty when the probe
 * fell back to the chat-completion path.
 */
sample_model_ids: Array<string>, };
