// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewComment } from "./ReviewComment";

/**
 * Request to publish a batch of local comments as a single GitHub
 * PR review. The `gh` shell-out (5.7.2) resolves the PR head SHA,
 * reconciles each comment's anchor against it, and posts the
 * survivors as one `event: COMMENT` review.
 */
export type PublishReviewRequest = { 
/**
 * Optional review-summary body (the top-level review comment).
 */
body: string | null, 
/**
 * The local comment drafts to publish. The backend decides
 * which actually post based on drift reconciliation.
 */
comments: Array<ReviewComment>, };
