// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of [`PublishReviewRequest`]. A tagged enum so the UI can
 * branch cleanly between "no PR to post to" and a successful post.
 */
export type PublishReviewResult = { "kind": "no_pr", branch: string, } | { "kind": "published", posted: number, lost: Array<string>, reviewUrl: string, };
