// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadFileResult = { 
/**
 * UTF-8 text content. Binary files surface a separate API later.
 */
text: string, mtime_ms: bigint | null, 
/**
 * Best-effort detection: true if the file looked binary and was not decoded.
 */
is_binary: boolean, };
