// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewSide } from "./ReviewSide";

/**
 * Where a [`ReviewComment`] points. The line numbers are a
 * fast-path *hint* for rendering; `fingerprint` is the truth used
 * to re-locate the anchor after the text shifts (see the
 * content-based anchoring section of the spec). When the
 * fingerprint can't be found near the hint the comment goes
 * "stale" in the UI rather than being dropped.
 */
export type ReviewAnchor = { 
/**
 * Workspace-relative path, matching [`crate::git::GitStatusEntry::path`].
 */
path: string, 
/**
 * Diff side the comment lives on.
 */
side: ReviewSide, 
/**
 * 1-based first line of the anchored range in the side's
 * *current* text. A hint — re-derived from `fingerprint` on
 * every section rebuild.
 */
startLine: number, 
/**
 * 1-based last line of the anchored range. Equal to
 * `start_line` for a single-line comment.
 */
endLine: number, 
/**
 * Hash of the trimmed text of the anchored line(s). The
 * source of truth for re-locating the anchor when line
 * numbers drift.
 */
fingerprint: string, 
/**
 * The merge-base / `HEAD` SHA the comment was written
 * against. Recorded so the publish path can tell how far the
 * world has moved since.
 */
baselineRev: string, };
