// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side of the diff a comment is anchored to — mirrors
 * GitHub's `LEFT` / `RIGHT`. `Working` (GitHub `RIGHT`) is the
 * added / unchanged-context side, i.e. the code as it will land;
 * `Base` (GitHub `LEFT`) is the deleted / old side. Comments
 * default to `Working`.
 */
export type ReviewSide = "base" | "working";
