// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewAnchor } from "./ReviewAnchor";

/**
 * One local-first review comment draft. One author (the user), one
 * body, one anchor — no threading or replies (deliberate non-goal,
 * see the spec). Persisted in [`crate::session::FolderSession::review_comments`]
 * until published to GitHub, then deleted locally.
 */
export type ReviewComment = { 
/**
 * Stable id (ULID) assigned on create. Used as the React-style
 * keyed-list identity in the UI and as the handle the publish
 * result reports back for "lost" comments.
 */
id: string, anchor: ReviewAnchor, 
/**
 * Markdown comment text.
 */
body: string, 
/**
 * RFC3339 creation timestamp.
 */
createdAt: string, };
