// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A per-file "Viewed" mark (GitHub's checkbox). Pinned to the blob
 * SHA of the version that was ticked; on every git-status refresh
 * the frontend re-validates against the file's current blob SHA
 * and auto-clears the mark when they differ, so a new commit
 * touching the file un-ticks exactly that file. Never published —
 * a purely local progress aid for reviewing a large diff across
 * several sittings. Persisted in
 * [`crate::session::FolderSession::reviewed_files`].
 */
export type ReviewedFile = { 
/**
 * Workspace-relative path of the reviewed file.
 */
path: string, 
/**
 * Blob SHA (`git hash-object`) of the version that was
 * ticked. The mark stays valid only while the file's current
 * blob SHA matches this.
 */
reviewedRev: string, 
/**
 * RFC3339 timestamp of when the file was marked reviewed.
 */
reviewedAt: string, };
