// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Surface mounted in the right-side panel. Chat and coder are
 * mutually exclusive; this enum encodes the pick. The slot can also
 * be closed entirely (`None` on `AppState::right_panel`).
 */
export type RightPanelKind = "chat" | "coder";
