// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouterPricing = { 
/**
 * USD per 1M input tokens.
 */
input: number, 
/**
 * USD per 1M output tokens.
 */
output: number, };
