// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One container in the compose project, as reported by
 * `docker compose ps --format json`.
 */
export type ServiceStatus = { 
/**
 * Compose service name (`dev`, `mongo`, `redis`, …).
 */
name: string, 
/**
 * Raw Docker container state (`running`, `paused`,
 * `exited`, `created`, `restarting`, `dead`). Forwarded
 * verbatim so the UI can show it without us re-encoding
 * nuance away.
 */
raw_state: string, 
/**
 * Process exit code. Compose emits `0` for non-exited
 * states too, so this is meaningful only when
 * `raw_state == "exited"`. The aggregation layer uses it
 * to distinguish a successful init container (exit 0)
 * from a failed long-running service (exit ≠ 0); the UI
 * surfaces it next to the state for `exited` services.
 */
exit_code: number, 
/**
 * Healthcheck verdict, when one is declared (`healthy`,
 * `unhealthy`, `starting`). Empty string when the service
 * has no healthcheck.
 */
health: string, 
/**
 * True when the container is up but attached to **no**
 * network — the residue of a failed start (typically a
 * host-port conflict) whose rollback wiped the container's
 * endpoint config. Such a service is unreachable by name
 * and publishes nothing, no matter how healthy it claims to
 * be, and only a recreate fixes it; the backend
 * auto-recreates on the next lifecycle action and the UI
 * surfaces it as failed meanwhile. Always `false` for
 * containers that aren't running (stopped containers hold
 * no endpoints, so the question is meaningless).
 */
networkless: boolean, };
