// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One container in the compose project, as reported by
 * `docker compose ps --format json`.
 */
export type ServiceStatus = { 
/**
 * Compose service name (`dev`, `mongo`, `redis`, …).
 */
name: string, 
/**
 * Raw Docker container state (`running`, `paused`,
 * `exited`, `created`, `restarting`, `dead`). Forwarded
 * verbatim so the UI can show it without us re-encoding
 * nuance away.
 */
raw_state: string, };
