// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One message inside a thread (or the parent itself). Phase 11.1
 * renders these read-only as bubbles; 11.2 will diff successive
 * snapshots to detect edits via `edited_ts`.
 */
export type SlackMessage = { 
/**
 * Stable Slack message ID. Sortable lexicographically.
 */
ts: string, 
/**
 * Author's Slack user ID. `None` only for system / unknown
 * messages, which we still render but flag as "unknown sender".
 */
user_id: string | null, 
/**
 * Plain text body. Slack's mrkdwn dialect is *not* parsed here —
 * 11.4 swaps in proper rendering. For now it's literally what
 * Slack returned, with `\n` preserved.
 */
text: string, 
/**
 * `edited.ts` when the message has been edited. Lets the UI
 * surface "(edited)" and lets 11.2's polling diff identify
 * changes without comparing the full body.
 */
edited_ts: string | null, 
/**
 * True when the author is a bot (per Slack's `bot_id` field on
 * the message). Used for bubble alignment + colour. Doesn't
 * distinguish *which* bot.
 */
is_bot: boolean, };
