// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Minimal user record for resolving `<@U12345>` mentions in
 * rendered Slack mrkdwn. Cached per-user on the frontend; the
 * backend just wraps `users.info`.
 *
 * `display_name` is what Slack shows next to the avatar; falls back
 * to `real_name` and finally `name` (the username slug). Callers
 * should prefer that order — see `bestLabel` on the frontend.
 */
export type SlackUserSummary = { user_id: string, name: string, real_name: string, display_name: string | null, is_bot: boolean, };
