// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One link button rendered under a message body. Always points at a
 * URL; we don't model interactive (`value`-only) buttons because a
 * read-only chat panel can't dispatch them anywhere useful.
 */
export type SlackAction = { 
/**
 * Button label (`text.text` from Slack — always `plain_text`).
 */
label: string, 
/**
 * Destination URL. Opened externally via `tauri-plugin-opener`,
 * same allowlist as message links (`http(s)` / `mailto`).
 */
url: string, 
/**
 * Optional Slack styling hint: `"primary"` / `"danger"`. The
 * renderer tints the button accordingly; missing means default.
 */
style: string | null, };
