// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlackBotProfile } from "./SlackBotProfile";

/**
 * Slack-specific slice of [`AppState`]. Only stores derived,
 * non-secret pointers so we can reload the chat panel on launch
 * without re-running the bot picker. Panel visibility lives at the
 * top level on [`AppState::right_panel`] — chat and coder share
 * one slot.
 */
export type SlackAppState = { 
/**
 * Bot the user picked from the DM list. `None` means "show the
 * picker on next chat-panel render". Cleared by an explicit "Pick
 * a different bot" gesture or when `auth.test` reports the token
 * is dead.
 */
active_bot: SlackBotProfile | null, 
/**
 * `thread_ts` of the session the user last had open in the chat
 * panel. Restored on launch so reopening the panel jumps back
 * into the same conversation. Cleared on bot switch and on
 * disconnect — bot pick and active thread are coupled (the
 * thread lives inside the bot's DM channel, ID encoded in
 * `active_bot.dm_channel_id`).
 */
active_thread_ts: string | null, };
