// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlackIdentity } from "./SlackIdentity";

/**
 * Connection status for the chat panel. The frontend polls this on
 * startup and after every `slack_set_token` / `slack_clear_token`.
 */
export type SlackStatus = { connected: boolean, identity: SlackIdentity | null, };
