// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlackBotProfile } from "./SlackBotProfile";

/**
 * Slack-specific slice of [`AppState`]. Only stores derived,
 * non-secret pointers so we can reload the chat panel on launch
 * without re-running the bot picker.
 */
export type SlackAppState = { 
/**
 * Bot the user picked from the DM list. `None` means "show the
 * picker on next chat-panel render". Cleared by an explicit "Pick
 * a different bot" gesture or when `auth.test` reports the token
 * is dead.
 */
active_bot: SlackBotProfile | null, };
