// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bot we can DM, discovered by scanning the authenticated user's
 * own DM list. See `specs/slack-chat.md#bot-resolution` for why we
 * don't search the workspace directory.
 *
 * Persisted (when the user picks one) in `AppState.slack.active_bot`
 * — non-secret, machine-local — so the picker doesn't reappear on
 * every launch.
 */
export type SlackBotProfile = { 
/**
 * Slack user ID (e.g. `U0AGNMHHQ1H`).
 */
user_id: string, 
/**
 * DM channel between the human and this bot. Comes straight from
 * `conversations.list?types=im` — Slack returns a stable channel
 * per `(human, bot)` pair so this never changes.
 */
dm_channel_id: string, 
/**
 * Slack `name` (e.g. `moon_bot`). Stable username slug.
 */
username: string, 
/**
 * `real_name` (e.g. `Moon Bot`). Empty string if Slack returns nothing.
 */
real_name: string, 
/**
 * `profile.display_name` when set; otherwise `None`.
 */
display_name: string | null, 
/**
 * Avatar URL (`profile.image_72` preferred, falling back to 48 / 24).
 */
image_url: string | null, };
