// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `auth.test`. Identifies the human whose token we hold.
 */
export type SlackIdentity = { 
/**
 * Slack user ID of the human (e.g. `U01ABCDE`).
 */
user_id: string, 
/**
 * Slack username (`real_name` field — what shows next to the avatar).
 */
user_name: string, 
/**
 * Workspace ID (e.g. `T01ABCDE`).
 */
team_id: string, 
/**
 * Workspace display name (e.g. `Hugging Face`).
 */
team: string, 
/**
 * Workspace base URL (e.g. `https://huggingface.slack.com/`).
 */
url: string, };
