// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One reaction group on a message — Slack collapses repeated
 * reactions of the same emoji into a single entry with a count.
 * We don't surface the per-reactor user list yet (no tooltip in
 * the read-only-minus-tooltip cut); when somebody asks, swap in a
 * `pub users: Vec<String>` and resolve via the existing
 * `userCache`.
 */
export type SlackReaction = { 
/**
 * Slack emoji shortcode without the surrounding colons
 * (e.g. `"thumbsup"`, `"rocket"`, `"custom_team_emoji"`).
 * May include a `::skin-tone-N` suffix on people emoji that
 * the reactor applied a skin-tone modifier to.
 */
name: string, 
/**
 * Number of users who reacted with this emoji. Always ≥ 1
 * (Slack drops the entry when the last reactor removes
 * theirs).
 */
count: number, };
