// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the human whose token we hold, plus enough chrome
 * (workspace icon) for the chat-panel header. Synthesised from
 * `auth.test` (user fields) plus `team.info` (icon). The latter
 * requires the `team:read` scope; it's part of the upfront grant.
 */
export type SlackIdentity = { 
/**
 * Slack user ID of the human (e.g. `U01ABCDE`).
 */
user_id: string, 
/**
 * Slack username (`real_name` field — what shows next to the avatar).
 */
user_name: string, 
/**
 * Workspace ID (e.g. `T01ABCDE`).
 */
team_id: string, 
/**
 * Workspace display name (e.g. `Hugging Face`).
 */
team: string, 
/**
 * Workspace base URL (e.g. `https://huggingface.slack.com/`).
 */
url: string, 
/**
 * Workspace icon URL (`team.info.icon.image_132` preferred,
 * falling back to smaller sizes). `None` when the workspace
 * uses Slack's auto-generated default icon (`image_default:
 * true`) — the panel renders a local initial-letter
 * placeholder instead, which is cleaner than embedding
 * Slack's generic glyph.
 */
icon_url: string | null, };
