// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryKind } from "./EntryKind";

export type StatResult = { kind: EntryKind, size: bigint, mtime_ms: bigint | null, };
