// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resolved OS colour-scheme preference. Emitted by the desktop shell
 * via the `system_theme` Tauri command; `Unspecified` is the third
 * XDG portal value that we treat as "fall back to dark" on the
 * frontend.
 *
 * Separate from [`ThemeMode`] because the OS can't express "follow
 * system" (it _is_ the system) and because conflating the two would
 * mask the `Unspecified` case we actually need to see.
 */
export type SystemTheme = "dark" | "light" | "unspecified";
