// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalTarget } from "./TerminalTarget";

/**
 * Open request payload for `terminal_open`. Cols/rows match
 * xterm.js's initial fit; the supervisor sends them straight
 * through to `PtySize` on the backend.
 */
export type TerminalOpenRequest = { target: TerminalTarget, cols: number, rows: number, 
/**
 * Command to run inside the fresh shell right after spawn
 * (typed in as if the user had typed it). Used by "restart"
 * on an exited tab and by session replay on IDE launch — the
 * frontend seeds it from the shell-history line it captured
 * when the terminal was last used, so the restored terminal
 * lands with its previous command already run and the rest
 * of the session's history available via up-arrow.
 */
command: string | null, 
/**
 * Absolute **host** path of the bound folder this terminal is
 * being opened for — the project the user was in when they hit
 * `+ Terminal`. Recorded in
 * [`moon_terminal::TerminalRegistry`] so the coder's
 * `list_terminals` / `read_terminal` tools can scope
 * themselves to the session's own project or worktree
 * (ADR 0048).
 *
 * Passed explicitly rather than derived from `cwd`: a worktree
 * rides its parent's bind mount, so its container `cwd` is a
 * path *under* the parent's folder, and any user `cd` makes
 * the shell's live cwd a lie about which project the terminal
 * belongs to. `None` for a terminal with no project behind it
 * (a `$HOME` shell in a folder-less workspace); those never
 * match a folder-scoped listing.
 */
folder: string | null, };
