// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The backend replaced a terminal's shell in place (agent
 * `restart`): same `stream_id`, fresh process. Emitted on
 * `terminal:respawned`.
 */
export type TerminalRespawned = { stream_id: string, };
