// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a terminal session ended. Classified by the supervisor
 * at close time so the frontend can tell "the user exited the
 * shell" (Ctrl+D, `exit` — code 0) from "the environment went
 * away" (container stopped mid-session, `docker exec` refused
 * because the container wasn't running yet). Drives the
 * auto-close / auto-respawn policy in `terminal.svelte.ts`:
 * shell exits close the tab, container losses keep it and
 * offer to respawn.
 */
export type TerminalCloseReason = "shell_exited" | "container_shell_exited" | "container_stopped" | "container_not_running" | "unknown";
