// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The backend closed a terminal (agent `close`); the tab goes
 * away. Emitted on `terminal:removed`.
 */
export type TerminalRemoved = { stream_id: string, };
