// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTerminal } from "./AgentTerminal";
import type { TerminalTarget } from "./TerminalTarget";

/**
 * An agent opened a terminal (`open_terminal`). The PTY is already
 * running under `stream_id`; the frontend adopts it as a tab.
 * Emitted on `terminal:agent_opened`, before any of its output.
 */
export type TerminalAgentOpened = { stream_id: string, target: TerminalTarget, folder: string | null, agent: AgentTerminal, };
