// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a terminal's shell process runs. Matches
 * `moon_terminal::TerminalTarget` 1:1 in shape; we keep this
 * copy in `moon-protocol` to avoid leaking that crate's
 * internals through `ts-rs` bindings.
 *
 * `Host` shells start in `cwd` (or the user's `$HOME` if
 * `cwd` is `None`). `Container` shells start in the
 * in-container path under `/workspace/<basename>` for the
 * active folder, picked by the frontend at open time so the
 * backend doesn't have to know about workspace layout.
 */
export type TerminalTarget = { "kind": "host", cwd: string | null, } | { "kind": "container", 
/**
 * Workspace id (`default` until multi-workspace
 * ships). The Tauri command derives the actual
 * `moon-ws-<id>-dev-1` container name from this.
 */
workspace_id: string, 
/**
 * In-container working directory. Required.
 */
cwd: string, };
