// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One chunk of terminal output. `data` is base64-encoded
 * bytes — feed straight into xterm.js's `write` after
 * decoding. Keyed on `stream_id` so multiple terminals don't
 * interleave (each tab subscribes to the bus and filters by
 * id). Emitted on the `terminal:output` Tauri event.
 */
export type TerminalOutput = { stream_id: string, 
/**
 * Base64-encoded raw bytes from the PTY master.
 */
data: string, };
