// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Final event for a terminal session, emitted exactly once
 * on `terminal:closed` when the underlying child exits. The
 * frontend marks the tab as no-longer-streaming and disables
 * input on receipt; subsequent `terminal_close` calls for
 * this id are no-ops.
 */
export type TerminalClosed = { stream_id: string, 
/**
 * Process exit code if portable-pty surfaced one.
 * `None` for signals it couldn't translate or for
 * supervisor-cancelled streams.
 */
code: number | null, };
