// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bookkeeping for one session's last successful Hub push.
 */
export type UploadedMarker = { 
/**
 * Length in bytes of the local JSONL when it was last
 * pushed. The runner short-circuits a re-upload when the
 * current on-disk length matches — Xet would dedup the
 * content anyway, but skipping the call entirely saves the
 * `xet-write-token` round-trip + the `batch` POST.
 */
bytes: bigint, 
/**
 * Wall-clock time (Unix ms) when the push landed. Surfaced
 * in the session-list "Synced 2m ago" tooltip. Purely
 * informational — sync decisions key off `bytes`.
 */
at_ms: bigint, };
