// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostKind } from "./HostKind";

export type Workspace = { id: string, name: string, root: string, host: HostKind, };
