// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceFolder } from "./WorkspaceFolder";

/**
 * The full workspace shape: a singleton `"default"` workspace
 * holding zero or more folders, with at most one currently active.
 */
export type Workspace = { id: string, 
/**
 * Insertion order. Drives the folder-bar order in the sidebar.
 */
folders: Array<WorkspaceFolder>, 
/**
 * Absolute path of the currently active folder. Always matches
 * some `folders[].path` when set; `None` only when the workspace
 * is empty.
 */
active_folder: string | null, };
