// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderSession } from "./FolderSession";

/**
 * Persisted UI session for one workspace. Holds one
 * [`FolderSession`] per bound folder, plus a pointer to which folder
 * was active at last save. Lives at
 * `<workspaces_dir>/<id>/session.json` from Phase 7.5 onward —
 * previously it was `AppState.last_session` in the global
 * `state.json`, and the IDE wipes that legacy slot on first run.
 */
export type WorkspaceSession = { 
/**
 * Folders bound into the workspace, in insertion order — same
 * order the folder bars render in.
 */
folders: Array<FolderSession>, 
/**
 * Absolute path of the active folder, if any. Must match one of
 * `folders[].folder_path` when set.
 */
active_folder_path: string | null, 
/**
 * Per-workspace lock on the coder's active provider. When set,
 * the runner ignores
 * [`crate::app_state::CoderAppState::active_provider`] for
 * this workspace and uses the locked value — so toggling the
 * global default from another workspace's modal doesn't bleed
 * into a workspace the user pinned. `None` (the default) means
 * "follow the global active_provider, just like before".
 *
 * This is per-workspace because a single user often runs
 * different repos against different providers (e.g. one repo
 * always against Anthropic for cache-friendliness, another
 * happily flipping between HF and OpenRouter). Storing the
 * lock here rather than in `AppState` keeps the global default
 * genuinely global while letting individual workspaces opt out.
 */
coder_provider_lock?: CoderProviderLock | null, };
