// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SplitSide } from "./SplitSide";

export type WorkspaceSession = { 
/**
 * Absolute path of the workspace folder. Used to re-open the same
 * workspace on the next launch and to invalidate stale sessions
 * when the user opens a different folder.
 */
workspace_path: string, 
/**
 * Tabs open in the left pane, in tab order, relative to
 * `workspace_path`. May reference files that no longer exist; the
 * frontend filters those out at restore time.
 */
open_files_left: Array<string>, 
/**
 * Tabs open in the right pane, in tab order, relative to
 * `workspace_path`. Empty when no split is active. The two lists
 * are independent — a file can live in one pane, both, or neither
 * (VSCode/Zed convention).
 */
open_files_right: Array<string>, 
/**
 * Active tab on the left pane, if any. Must appear in `open_files_left`.
 */
active_left: string | null, 
/**
 * Active tab on the right pane, if any. `None` when the split is
 * closed; `Some` only makes sense alongside `has_split = true`.
 */
active_right: string | null, has_split: boolean, focused_side: SplitSide, };
