// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderOrigin } from "./FolderOrigin";
import type { HostKind } from "./HostKind";

/**
 * One folder bound into a workspace.
 */
export type WorkspaceFolder = { 
/**
 * Absolute, canonicalised path on the host.
 */
path: string, 
/**
 * Display label (basename of `path` at add-time). Folder rename
 * is a Phase 7 follow-up, so this is fixed for the folder's life
 * in the workspace.
 */
name: string, host: HostKind, 
/**
 * How this folder came to be bound. Defaults to
 * [`FolderOrigin::UserPicked`] — the only kind before
 * worktree-backed coder sessions (ADR 0028). `#[serde(default)]`
 * keeps older snapshots loading cleanly.
 */
origin: FolderOrigin, };
